name: e_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_stateful_bloc:
    git:
      url: git@github.com:Mohamed-Shalabi/flutter-stateful-bloc.git
      ref: dev
  equatable: ^2.0.5
  flutter_svg: ^1.1.4
  path_provider: ^2.0.11
  path: ^1.8.2
  intl: ^0.17.0
  sqflite: ^2.0.3+1
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/media/images/
